name: Schema Compatibility

on:
  pull_request:

jobs:
  schema-compat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest jsonschema

      # Schema専用の最小テストだけを実行（他のテストは通常CIで走る）
      - name: Run schema unit test
        run: pytest -q tests/test_schema_required.py

      # ベースブランチを取得（origin/<base_ref> をローカルに作る）
      - name: Fetch base branch
        run: |
          git fetch --no-tags --prune --depth=1 origin "${{ github.base_ref }}"

      - name: Check schema compatibility
        run: |
          python tools/check_schema_compat.py \
            --base "origin/${{ github.base_ref }}" \
            --path "schemas/minutes.schema.json"
